name: FirstPersonFightCraft
main: com.jdub03.spectorgadgetz.FirstPersonFightCraft.FirstPersonFightCraft
version: 1.0

commands:
lordcmos:
     description: This is a demo command.
     usage: /lordcmos [player]
     permission: FirstPersonFightCraft.lordcmos
     permission-message: You don't have <permission>