name: {FirstPersonFightCraft}
main: {com.jdub03.spectorgadgetz.FirstPersonFightCraft.FirstPersonFightCraft}
version: {1.0}

command:
  lordCmos:
        description: This is a demo command.
        usage: /<command> [player]
        permission: <FirstPersonFightCraft>.basic
        permission-message: You don't have <permission>