name: FirstPersonFightCraft
main: com.jdub03.spectorgadgetz.FirstPersonFightCraft.FirstPersonFightCraft
version: 1
author: mrgadgetz
commands:
  lordcmos:
    description: 'Give yourself items.'
    usage: '/lordcmos [itemid] <amount> where itemid is the item you want and amount is number of items'
    permission: FirstPersonFightCraft.lordcmos
    permission-message: 'You don''t have <permission>'

permissions:
  FirstPersonFightCraft.lordcmos:
    description: Give yourself items.
    default: true



